// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://thjrmrrfervsytryxyjq.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InRoanJtcnJmZXJ2c3l0cnl4eWpxIiwicm9sZSI6ImFub24iLCJpYXQiOjE3Mzk3NTUyNTMsImV4cCI6MjA1NTMzMTI1M30.xwVU36joeJD9CEDPf6aiJ8v93juti5J5EexmT7LBqg4";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);